
spring:
  datasource:
    url: jdbc:mysql://139.196.233.99:3306/quartz_demo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&failOverReadOnly=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
#  quartz:
#    job-store-type: jdbc
#    jdbc:
#      initialize-schema: always
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 10

logging:
  config: classpath:log4j.properties
